# Generated by Django 5.2.17 on 2026-09-30 20:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('market', models.CharField(choices=[('synthetic', 'Derived / Synthetic'), ('forex', 'Forex'), ('commodity', 'Commodities'), ('stock', 'Stocks')], max_length=12)),
                ('submarket', models.CharField(blank=True, max_length=40)),
                ('kind', models.CharField(choices=[('gbm', 'Random walk'), ('boom', 'Boom (spikes up)'), ('crash', 'Crash (spikes down)')], default='gbm', max_length=6)),
                ('spike_every', models.PositiveIntegerField(default=0)),
                ('base_price', models.FloatField()),
                ('volatility', models.FloatField(help_text='Std-dev of relative move per sqrt(second)')),
                ('tick_interval', models.FloatField(default=1.0)),
                ('decimals', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='2547XXXXXXXX', max_length=15)),
                ('country', models.CharField(default='KE', max_length=2)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('demo', 'Demo'), ('real', 'Real')], max_length=4)),
                ('login_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('tool', models.CharField(max_length=20)),
                ('points', models.JSONField(default=list)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('RISE', 'Rise'), ('FALL', 'Fall'), ('HIGHER', 'Higher'), ('LOWER', 'Lower'), ('TOUCH', 'Touch'), ('NOTOUCH', 'Notouch'), ('ACCU', 'Accu'), ('MULTUP', 'Multup'), ('MULTDOWN', 'Multdown'), ('DIGITMATCH', 'Digitmatch'), ('DIGITDIFF', 'Digitdiff'), ('DIGITOVER', 'Digitover'), ('DIGITUNDER', 'Digitunder'), ('DIGITEVEN', 'Digiteven'), ('DIGITODD', 'Digitodd')], max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('sold', 'Sold')], db_index=True, default='open', max_length=5)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=14)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payout', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, max_length=1)),
                ('barrier', models.FloatField(blank=True, null=True)),
                ('prediction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('multiplier', models.PositiveIntegerField(blank=True, null=True)),
                ('growth_rate', models.FloatField(blank=True, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('start_epoch', models.FloatField()),
                ('entry_epoch', models.FloatField(blank=True, null=True)),
                ('expiry_epoch', models.FloatField(blank=True, null=True)),
                ('exit_epoch', models.FloatField(blank=True, null=True)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('ticks_elapsed', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.account')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.instrument')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.BigIntegerField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='api.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('payout', 'Payout'), ('sale', 'Sale'), ('adjustment', 'Adjustment')], max_length=10)),
                ('method', models.CharField(choices=[('mpesa', 'Mpesa'), ('card', 'Card'), ('paypal', 'Paypal'), ('bitcoin', 'Bitcoin'), ('internal', 'Internal')], default='internal', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=10)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.account')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contract')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'account_type'), name='one_account_per_type'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['instrument', 'status'], name='api_contrac_instrum_da520e_idx'),
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(fields=['instrument', '-open_time'], name='api_candle_instrum_7f0314_idx'),
        ),
        migrations.AddConstraint(
            model_name='candle',
            constraint=models.UniqueConstraint(fields=('instrument', 'open_time'), name='uniq_candle'),
        ),
    ]
